#ifndef VEG_PROLOGUE
#error "missing prologue"
#endif
#undef VEG_PROLOGUE

#undef VEG_DECLVAL
#undef VEG_DECLVAL_NOEXCEPT
#undef VEG_DEDUCE_RET
#undef VEG_HAS_BUILTIN_OR_0
#undef VEG_HAS_BUILTIN_OR_1
#undef VEG_HAS_BUILTIN_OR
#undef VEG_DEF_CONCEPT_FROM_BUILTIN_OR_TRAIT
#undef VEG_DEF_CONCEPT_FROM_BUILTIN_OR_STD
#undef VEG_INTERNAL_ASSERT
#undef VEG_CPP14
#undef VEG_CPP17
#undef VEG_CPP20
#undef VEG_HAS_BUILTIN
#undef VEG_IGNORE_CPP14_EXTENSION_WARNING
#undef VEG_NOM_SEMICOLON
#undef VEG_ABI
#undef VEG_ABI_VERSION
#undef VEG_DOC
#undef VEG_DOC_LOCATION
#undef VEG_DOC_FN
#undef VEG_DOC_CTOR
#undef VEG_DOC_CLASS
